[metadata]
name = quickfix
version = 1.16.0
description = FIX (Financial Information eXchange) protocol implementation
long_description = file: README.md
long_description_content_type = text/markdown
author = Oren Miller
author_email = oren@quickfixengine.org
maintainer = Oren Miller
maintainer_email = oren@quickfixengine.org
url = http://www.quickfixengine.org
download_url = http://www.quickfixengine.org
license_files = LICENSE

[options]
py_modules =
    quickfix
    quickfixt11
    quickfix40
    quickfix41
    quickfix42
    quickfix43
    quickfix44
    quickfix50
    quickfix50sp1
    quickfix50sp2
python_requires = >=3.6
